stages:
    - module-pipeline

RetroDockerTask3:
    stage: module-pipeline
    trigger:
        include:
            - /Task3/.gitlab-ci.yml
        strategy: depend
    only:
        changes:
            - Task3/**/*
